### PR TITLE
Demoin example

### PR DESCRIPTION
**Pull request by dsuarez**
Demoin example (init.d script and daemonize python pymouse script)
Changes in unix.py in order to allow submitting of a display parameter to the classes.

### CODE REVIEW

**Comment by ponty** [comment]
Unit-tests are broken after adding the display parameter.
It is not clear why it is set to ':0'.
I think the current display number should be used by default.

``` python
def __init__(self, display=':0'):
```

**Comment by pepijndevos** [comment]
I remember having some breakage with an empty string, unless you mean something else with "current display". But that might have been while testing the X11 backend on Mac.

So go ahead, change it, test it, I'll click the merge button.

That is as much maintenance as I'm currently doing on PyMouse, clicking merge buttons. I'm not using it at all, so I'm hoping someone will take over sometime.

**Comment by ponty** [comment]
I meant this question for @dsuarez: 
Is display=':0' really necessary?

I can see 2 solutions:

removing the display parameter:

``` python
def __init__(self):
```

or setting the default to None:

``` python
def __init__(self, display=None):
```

**Comment by pepijndevos** [comment]
I'd say None, as you might want to do stuff on multiple displays.

**Comment by dsuarez** [comment]
Hello, I dont really remember why I set default to :0, but probably due to
my custom environment. Probably a None as argument is more general.

On Sat, Dec 1, 2012 at 8:37 PM, ponty notifications@github.com wrote:

> I meant this question for @dsuarez https://github.com/dsuarez:
> Is display=':0' really necessary?
> 
> I can see 2 solutions:
> 
> removing the display parameter:
> 
> def **init**(self):
> 
> or setting the default to None:
> 
> def **init**(self, display=None):
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/pepijndevos/PyMouse/pull/18#issuecomment-10921822.

## 

http://facebook.com/wantudu--
David Suárez Perera dsuarez@gmail.com

**Pull request merged**
